### PR TITLE
Readme Questions idea generation

### PR DESCRIPTION
**Pull request by CodyMWilson**
Hey! I found your project a few days ago. I'd love to help contribute, and as a start I just had a few ideas for your unsolved multiplayer questions. Pardon any dumb ideas -it's been over 4 years since I last played EV Nova. I LOVE this project though, as NOVA (and AMBROSIA games) were a big part of my childhood growing up. My first game ever was Harry the Handsome executive. 

I'd love to contribute in other ways but I'm a total newb when it comes to javascript so it will probably be a slow learning curve (I've done C programming mostly).

### CODE REVIEW

**Comment by nicholasburka** [comment]
okay i've been following this project for a while - incredible & impressive work - and also loved EV Nova as a kid & have revisited numerous times since. i've held off on trying to contribute because i'm busy enough & because it seems you've been rebuilding the basic game infrastructure. but since you had the drive to comment Cody, i'm jumping in because i've been excited about someday contributing to unsolved multiplayer questions. somewhere down the line, it'd be cool to contribute to the code, too (i have some js/node/webdev experience) but no promises.

universes + player limits - i think this should be server config'd. i think having a cap like you said Cody makes sense for players who want a closed experience with the classic storylines occurring effectually universe wide. but personally would love to see servers with up to 100 players at any time universe wide (with a cap within a given galaxy at once given whatever the technical limits may be), probably requiring an overhaul of the storyline system if not complete abandonment to begin with. and eventually, would be incredible to see something like, a player becomes a high-tier Polaris, can issue a storyline to those involved in the Polaris storylines to, say, hold a covenant over a week and allow other players to visit Nil'a Mjolnir to vote to invade Federation space. at that rate, it'd also be neat to let players have a credit store in a bank on a particular planet, or back-up ships they've purchased at a planet, though maybe they'd have to successfully escape pod their way back - how hardcore to be about player deaths could be server configured too.

about hailing - i like both of your ideas about this. what about a "radio frequency" system where players can adjust their hailing frequencies / cycle through them. players could hail each other directly - "Cobra Starship is hailing at 1100[insert realistic space-time frequency unit] - _message _text".__ something that allows direct hailing/messaging, and open channels that other people could pick up on. this could integrate with existing NPC systemwide messages. maybe could even have items that allow different behaviors / abilities with respect to radio frequencies (jammers, spammers, scanners to listen into private hails, cross-galaxy hailing). and down the road, maybe could even include VoIP support...

saving - i think players should have to land to save, to prevent cheap quits in the middle of battles/chases. otherwise, their ship could be made direlict automatically. (with the usual chance of drop bear encounters on login)

a lot of ideas!

**Comment by nicholasburka** [comment]
i don't mean to suggest Matt you simply adopt these ideas/agree with them or build them alone - down the road i'd love to put some time into implementing whatever you and any other contributors/community come up with if you do want help, i just can't commit (heh heh).

**Comment by CodyMWilson** [comment]
> okay i've been following this project for a while - incredible & impressive work - and also loved EV Nova as a kid & have revisited numerous times since. i've held off on trying to contribute because i'm busy enough & because it seems you've been rebuilding the basic game infrastructure. but since you had the drive to comment Cody, i'm jumping in because i've been excited about someday contributing to unsolved multiplayer questions. somewhere down the line, it'd be cool to contribute to the code, too (i have some js/node/webdev experience) but no promises.
> 
> universes + player limits - i think this should be server config'd. i think having a cap like you said Cody makes sense for players who want a closed experience with the classic storylines occurring effectually universe wide. maybe in these, only one person could take a given storyline at a time. i haven't looked at how mission string system changes are coded in EV Nova, so I don't know if one storyline can co-exist with another and have both change the universe simultaneously.
> 
> personally would love to see servers with up to 100 players at any time universe wide (with a cap within a given galaxy at once given whatever the technical limits may be), probably requiring an overhaul of the storyline system if not complete abandonment to begin with. and eventually, would be incredible to see something like, a player becomes a high-tier Polaris, can issue a storyline to those involved in the Polaris storylines to, say, hold a covenant over a week and allow other players to visit Nil'a Mjolnir to vote to invade Federation space. at that rate, it'd also be neat to let players have a credit store in a bank on a particular planet, or back-up ships they've purchased at a planet, though maybe they'd have to successfully escape pod their way back - how hardcore to be about player deaths could be server configured too.
> 
> about hailing - i like both of your ideas about this. what about a "radio frequency" system where players can adjust their hailing frequencies / cycle through them. players could hail each other directly - "Cobra Starship is hailing at 1100[insert realistic space-time frequency unit] - _message _text".__ something that allows direct hailing/messaging, and open channels that other people could pick up on. this could integrate with existing NPC systemwide messages. maybe could even have items that allow different behaviors / abilities with respect to radio frequencies (jammers, spammers, scanners to listen into private hails, cross-galaxy hailing). and down the road, maybe could even include VoIP support...
> 
> saving - i think players should have to land to save, to prevent cheap quits in the middle of battles/chases. otherwise, their ship could be made direlict automatically. (with the usual chance of drop bear encounters on login)
> 
> a lot of ideas! i'd love to someday help implement whatever is decided, though i can't commit (heh). i'm also glad to continue brainstorming and talk through ideas, but Matt i don't want to pester you as an idea guy on your 1100 commit project. either way... amazing game & project

I just wanted to say that the generation of discussion that my merge request created gave me a huge smile :)

Your idea on having people already in a faction gave me an idea: what if there was a new system where someone with a high faction rank could create missions for others? I'm thinking:

1. A 'create mission' button
2. Select from
    *Cargo
    *Destroy
3. Cargo:
    *Select pickup system
    *Select destination system
4. Destroy
    *Select system (or sector)
    *Select difficulty (will generate a ship based on these vals)
5. Select rank val increase

A few other ideas:

- Perhaps rank in a faction should be turned into a numeric val that can be increased and decreased from quests already in the game, but also by user quests?
- Perhaps the stardate for quests could be changed for a real-life in-game time, so for a delivery quest you have a number of hours or minutes to make the delivery

I like your thought of having 100+ players, it certainly creates a great scope. My thoughts on having small groups are
- A smaller goal is more achievable
- My experience with games is that they are much more fun with friends rather than huge experiences - I'm also not sure if the galaxy map in NOVA can really support more than a handful of people without feeling congested
- A smaller experience feels more impactful, especially when large groups of players goals can quickly dwarf and individual players. In a game where you shape the outcome I think it's important that every player feels like their actions in the universe affect the outcome

Thank you so much for generating discussion on my thoughts!

**Comment by mattsoulanille** [comment]
I'm glad to see people interested in the project, and the discussion here is great! I've been trying to get this project to a state where others can contribute, and I think most of the infrastructure (continuous integration and deployment of the demo) is ready. What I haven't done yet is document the code I've written so far, the design ideas I have, and the scope of the project. Once that's more complete, I'll have a better idea of how people can help.

I'll write some documentation and add my comments to your ideas this weekend, and I'll also add some starter issues in case people are interested in contributing (if I can think of some good ones).

You might also be wondering why I'm still working on this project now that [Cosmic Frontier: Override](https://www.kickstarter.com/projects/cosmicfrontier/cosmic-frontier-override/) is well into its development. Perhaps I'm just stubborn, but I started this project several years before Cosmic Frontier was announced, and I guess I just want to see it to completion. I also like how it lets me explore different technologies that I probably wouldn't otherwise use, and I just think it's a fun thing to work on. Nova was a large part of my childhood, so that's definitely part of it too.

**Comment by nicholasburka** [comment]
Exciting! I've never played EV: Override, but IMO the universe of EV Nova is more interesting (graphics, sound fx included). 
Also the potential for multiplayer support seems like a huge addition. Looking forward to reading your plans/run-down and comments.

Cody, thanks for putting your thoughts out there! I like the mission idea. I understand the enjoyment of intimate and well-contained play thrus and can see how your third point about larger/more experienced groups would create issues - I'm thinking of players with Kestrels flying around and zapping starting traders. Balancing that would require serious NPC firepower around major systems pretty consistently.

I think a larger / persistent server for the general EV Nova community could lend itself better to the factional rank ideas, and would be interesting to see evolve over time with power struggles, etc. Giving players control over missions, Bar random events on controlled planets, etc could keep the universe feeling alive even if there are only a few players online at a time (tho again, big scope & Nova had a lot to return to as it was). Given the stated goal for Plug-In support, seems like this is something that could be, to some extent, updated + configured via Plug-Ins if not more directly. A simpler system for a general server could have a galaxy's state as a pastiche of the regular state of the system + the active players modifiers based on their place in their mission strings, and allow clashes between whatever fleets are tailing a player/invading/etc. Or could be a full-on Dark Souls like system where you can see other ships, maybe even invite to duel, but generally exist in your own world/save state.

**Comment by CodyMWilson** [comment]
Hi Matt,

Thanks for understanding! :) I did look for a discussion or issue tab since I know that making a merge request just for some suggestions is a bit unconventional.

I had no idea about cosmic frontier but honestly diving into the source code sounds a lot more fun. Out of curiosity - how did you get access to it? 

> Or could be a full-on Dark Souls like system where you can see other ships, maybe even invite to duel, but generally exist in your own world/save state.

**EV: SOULS**
 
Man everything gets compared to Dark Souls at some point or another. But honestly: I like the dual idea.

**Pull request closed without merging**
